version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: my_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}

#  app:
#    build: .
#    volumes:
#      - ./scrapped_data:/scrapped_data
#    environment:
#      - $(cat .env | xargs)
#    depends_on:
#      - neo4j

